### ISSUE TITLE
Minimum GPU Memory Requirement for Running the Experiment

### ISSUE THREAD

**Issue by JustCoolPig** [LightChen233/M3CoT#1]
Hello,

I recently came across your research paper and noticed that you have conducted your experiments using NVIDIA A100 and A800 GPUs. I am very interested in following your work. However, the memory of my current GPUs may not be sufficient to excute the program, and I am concerned about the minimum GPU memory requirements for running your experiment.

Could you please provide information on the minimum GPU memory requirement to successfully execute the experiments in your repository? It would be greatly appreciated if you could share any possible workarounds or suggestions for running the experiments on GPUs with lower memory capacities.

Thank you in advance for your time and assistance. I am looking forward to your response.

Best regards

**Comment by LightChen233** [comment]
I apologize for not addressing your issue earlier. Our tested open-source models typically range from 7B to 18B parameters. For models with 13B parameters or more, at least two GPUs with 24GB of memory each are required [1].

[1] https://github.com/haotian-liu/LLaVA
