### ISSUE TITLE
Inconsistent results from reproduction and in the paper

### ISSUE THREAD

**Issue by simplelifetime** [LightChen233/M3CoT#2]
Reproduction for LLaVA-13B has only 27.05% accuracy, which is far less than reported in the paper. What's wrong? 
Here is my script:
python evaluate.py --setting zero-shot \
                   --model llava-13b \
                   --prompt direct \
                   --metric_by domain

**Comment by LightChen233** [comment]
We appreciate your interest in our research. As demonstrated in Figure below, the accuracy score for the direct method reported in our study is indeed 27.05%.

<img width="745" alt="200806bb24627724b95849224129541" src="https://github.com/LightChen233/M3CoT/assets/62886885/d91224b8-a24f-4a0b-a785-30222a4ce6c4">

**Comment by simplelifetime** [comment]
Sorry I didn't notice that. However, why is the result of LLaVA-7B much better than LLaVA-13B under "direct" setting. This makes me very confused

**Comment by LightChen233** [comment]
This question is indeed interesting, but we haven't found a good explanation. It appears that for the backbone of LLaVA-13B, the performance of LLama-13B can not consistently surpass that of its 7B version in direct setting. And this disparity may be attributable to differences in their respective training regimes.
