### ISSUE TITLE
Is this a mistake? ID: physical-commonsense-1426

### ISSUE THREAD

**Issue by jungao1106** [LightChen233/M3CoT#3]
In HF pre-viewer. The answer of first training instance is C
<img width="735" alt="截屏2024-07-26 22 33 56" src="https://github.com/user-attachments/assets/676ddfca-9076-44a3-bcf1-d02f1f12b0dc">

However, the answer seems D according to the rationale.
<img width="145" alt="截屏2024-07-26 22 35 38" src="https://github.com/user-attachments/assets/5aba9f3b-8781-4157-8573-8ec34258df7e">

I consider the answer is D too.

**Comment by LightChen233** [comment]
Thank you for your issue. Your opinion is right, we will fix this problem as soon as possible

**Comment by LightChen233** [comment]
Thank you for your attention to our work, we have revised this data on the latest m3cot data
