### ISSUE TITLE
Question about Multi-Image Input for LLaVA-v1.5 in Section 5.4.2

### ISSUE THREAD

**Issue by lky-violet** [LightChen233/M3CoT#6]
Thank you for your outstanding work! While reading Section 5.4.2 In-Context-Learning Exploration, I noticed that you conducted ICL tests with mixed image-text examples using LLaVA-v1.5.
However, in my previous experiments with LLaVA-v1.5, I found that it does not support multi-image input, which is also mentioned in the LLaVA GitHub issues. Therefore, I would like to ask how you handled image inputs as part of ICL for LLaVA. Did you perform any specific modifications or use additional operations?

**Comment by lky-violet** [comment]
May I ask if adding multiple images requires fine-tuning?

**Comment by LightChen233** [comment]
We don't have many pictures. To ensure variable control and fair comparison, We use the most traditional instruction-tuning method for fine-tuning.

**Comment by lky-violet** [comment]
Is this the format for instruction fine-tuning data?  

SHOT 1  
<img> IMAGE EMBEDDING </img>  
TEXTUAL TOKENS  

SHOT 2  
<img> IMAGE EMBEDDING </img>  
TEXTUAL TOKENS

**Comment by LightChen233** [comment]
Sorry, maybe my expression was not very clear. We **did not** perform fine-tuning of **multiple images**. The following format is the prompt format only used in our **inference** process:
```python
# SHOT 1
<img> IMAGE EMBEDDING </img>
TEXTUAL TOKENS
# SHOT 2
<img> IMAGE EMBEDDING </img>
TEXTUAL TOKENS
```

**Comment by lky-violet** [comment]
Thank you so much for your patient reply!
