### ISSUE TITLE
Question about missing test dataset images when using Google Drive

### ISSUE THREAD

**Issue by lky-violet** [LightChen233/M3CoT#7]
Thank you for your outstanding work and for providing the open-source dataset! While using your dataset, I noticed that loading the dataset via Hugging Face works perfectly. However, when I used the "load Dataset from Google Drive" method, I found that the data folder extracted from the downloaded files is missing the test dataset images.
I managed to find the test images at this link: https://github.com/LightChen233/blog-img/tree/main/m3cot-image. Could you please confirm if I need to download additional images from this link or elsewhere to complete the dataset?

**Comment by LightChen233** [comment]
Sorry for misleading you.
The index of the dataset in Google Drive appears to be the index of our internal version. We will modify the corresponding data in the next update.

Additionally, we still recommend you to download the data in huggingface by the following command:
```shell
git clone https://huggingface.co/datasets/LightChen2333/M3CoT
```
or
```shell
huggingface-cli download --resume-download --repo-type dataset LightChen2333/M3CoT
```

**Comment by lky-violet** [comment]
Thank you so much for your reply!
